### PR TITLE
Upgrade hermit for release 0.1.11

### PR DESCRIPTION
**Pull request by nash-w**
Change was slightly more involved since the download location of TRH / TUC changed with version 0.1.11. There are now two recipe buckets: versions 0.1.5-> 0.1.10 and later releases

### CODE REVIEW

**Review by syncom — DISMISSED** [review]
Thanks for the contribution, @malapropistic ! :shipit:

**Comment by syncom** [comment]
Ah, I forgot to mention that this repo requires that all commits be signed. You may want to re-sign your commits and force push. I'll stamp it again.

**Comment by syncom** [comment]
@malapropistic Thanks for signing the commit. Your signature shows up as "Unverified". I was wondering if it's because the public key has not been added to GitHub.

**Review by syncom — DISMISSED** [review]

**Comment by nash-w** [comment]
Ya, I'm working thru the kinks -- I'll get there 😄

**Pull request closed without merging**
